<a href="https://colab.research.google.com/github/talhanoor23/my-projects/blob/main/Genetic-Mutation-Detection-System/01_Data_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!apt-get update
!apt-get install -y samtools

In [ ]:
!wget https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz
!gunzip variant_summary.txt.gz

In [ ]:
!wget https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
!gunzip hg38.fa.gz
!samtools faidx hg38.fa

In [ ]:
import pandas as pd

df = pd.read_csv("variant_summary.txt", sep="\t", low_memory=False)

In [ ]:
df

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
0,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,...,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
1,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,...,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
2,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,...,G,-,-,-,-,-,-,SCV000020156,-,-
3,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,...,G,-,-,-,-,-,-,SCV000020156,-,-
4,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,"Jun 29, 2015",150829393,...,A,-,-,-,-,-,-,SCV000020157,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6866039,3894784,single nucleotide variant,NM_017617.5(NOTCH1):c.1193G>A (p.Cys398Tyr),4851,NOTCH1,HGNC:7881,Uncertain significance,0,"Apr 01, 2024",-1,...,T,-,-,-,-,-,-,SCV005911581,-,-
6866040,3894785,single nucleotide variant,NM_001356.5(DDX3X):c.1526A>T (p.Asn509Ile),1654,DDX3X,HGNC:2745,Likely pathogenic,1,"Apr 01, 2024",-1,...,T,-,-,-,-,-,-,SCV005911582,-,-
6866041,3894785,single nucleotide variant,NM_001356.5(DDX3X):c.1526A>T (p.Asn509Ile),1654,DDX3X,HGNC:2745,Likely pathogenic,1,"Apr 01, 2024",-1,...,T,-,-,-,-,-,-,SCV005911582,-,-
6866042,3894786,Duplication,NM_015335.5(MED13L):c.3191dup (p.Thr1065fs),23389,MED13L,HGNC:22962,Pathogenic,1,"Apr 01, 2024",-1,...,GC,-,-,-,-,-,-,SCV005911583,-,-
6866043,3894786,Duplication,NM_015335.5(MED13L):c.3191dup (p.Thr1065fs),23389,MED13L,HGNC:22962,Pathogenic,1,"Apr 01, 2024",-1,...,GC,-,-,-,-,-,-,SCV005911583,-,-

In [ ]:
df.info()

In [ ]:
df["Assembly"].unique()

array(['GRCh37', 'GRCh38', 'na', 'NCBI36'], dtype=object)

In [ ]:
df.shape

(6866044, 43)

In [ ]:
df["AlternateAlleleVCF"].unique()

array(['TGCTGTAAACTGTAACTGTAAA', 'G', 'A', ..., 'AGCGCAGCATCATG',
       'CTATAGT', 'GCCGCCAGCCGCGGCCA'], dtype=object)

In [ ]:
df["ReferenceAlleleVCF"].unique()

In [ ]:
df_hg19 = df[df["Assembly"] == 'GRCh37']
df_hg38 = df[df["Assembly"] == 'GRCh38']
df_unknown = df[df["Assembly"].isin(['na', 'NCBI36'])]

In [ ]:
df_hg38.shape

(3401245, 43)

In [ ]:
df_hg19.shape

(3452941, 43)

In [ ]:
print("Before cleaning df_hg38:", df_hg38.shape)

Before cleaning df_hg38: (3401245, 43)

In [ ]:
df_hg38["ReferenceAlleleVCF"].unique()

array(['GGAT', 'GCTGCTGGACCTGCC', 'G', ..., 'ACCCGCAGGAGTTCATGAAGGCC',
       'GCTCTGTCCACAGGGATGCTGCCTGACCCCAAGAA',
       'TCCGGAAAAACTTTTTTTAAAAAATTAGCCGGGTGTGGTGGTGCATGCCCGTGGTGCCAGCTACTTAGAGGGCTGAGGTGGGATGACCCGTAAGCCCCGGAGGTCGAGGCTGCAGTGAGCCGTGATCGCGTCACTGCACTCAGACTGGACGACAGCGCGAGACCTGTCTCAAAAAAAAATAACAAGGGGTAGGGTGGGGCAGTGAGATGGTTCAGCGTTGTTCCCAAGGAACTCATCTCCCTAAATTTCCAGTCTCAAGCGCCGCTTTCATTCCCTGCCCCGAGCGGCGCTCCCCGCTCCGTGCACGCATCTCCGCTGAGGGCCGCCCTGACGCACGGCCTTCTGCCTTGAACACAGAACCCCTCAGCCCTTCCTATTAGCCGTTTCTGGCCGGGACTGCACGCGCTCCTTCCTGCCTCGGGGCGCAGGGTGAGACTTACGTCTAAAGGGCGCCCGGCGAGCTCGCAGCAGCCCCTGCCCCGCGGAGGGCCGGTGGCGCGCGGCGTCCGGTGAGGGGCAGCGGCCCGGGCTCGGTTCCGGCTTCCAGCAGCGGCCCGAAGGCGCCGGAGCACGCTCCCCGCTCCCCAGAACGCAGCTTCCGCGGCTGCAGCCCAGGCAGCTCTTCGGGAAGCGTCCGCCCGTGGTCTCGCCAGGGGGTTTCCGACCTCCCCGCCCGACAGCGCAGGGGCGGGGGCCGCGGCCGGAGAGCTCGCCCGAGAGCACCCCCTCCCGCTGCGCCTCTGGGCGCACGCGCAGCCGCTGCAGCCTCCCTTATTTAGTCCGCGATGGCTTCCCTCGCGCCCCACCGTCCTCTTCCGGAAGGCGGCTCCCTCCCTGCGCAGCCCGGAGCCCCTGAGATCAGCCTCGAGCAGGCGCCCGAGCGAGACTATCCCTAAACGGGAACGGCGGTGGCCGACTCGCGAGTGAGGAAAAGAAGGAAAGGGCAGACTGGTCGCGAAGAGAAGATCCAGGCCTCAGAGGAGGAGAAAGGCCGGAGCCAGCCGAGGTTTGCCGAGGGCGGTGTTCCGGACCCGCGCGGTGCGGGGAGGAAGGCCGAGGGTGGGAGAGGAGGGGCCCGGCGGAAACTGCCGAGGTTTCCCGAAGGCGGCAGCGTCCGAGTTGCCCGGATGTAGTTGGTGGAGCGGCAGCGGCGGCACCAGCGGCGGCGGCGGCGGCGGGAGGAGGAGGAGGAGAAGAAGGACCAGGCGGCGGCAGCAGCGGCGGCGGCGGGGGGAGGAGGGGAGGAGGCGGCGGAGCAGGAGGAGGAGAAGGCGGAGGAGGCAGTCGCTCTCCGCGGGGCTGAGCCGGACGCGTCGTCTTGCCCCCCTCCCCCCGGTTCGCGGTGCCGCCGTGTAGTTGGCGCCGCTGCCCCGGCTGAGAGTGAGCGTGGTGTCGACGGAGGGAGATGGCCCGGGAGCGCCGGCGCCAGTAACTGGGAGCTGATGAGAGTCGCCGAGGGCGCGCCGGGCCCAGGTGCCGGGGCTGCCCGCCGCCCGCCGCCGCCGCCGCCTGCGCGCCCGCCCGCCTTTCGCGGCCGCTCTCCCCCCTCCCCGACACACACTCACAGGCCGGGCATTGATGGTAATGTATGCGAGGAAACAGCAGAGACTCAGTGATGGGTAAATTGTCTTTTCGTTTCGGGCCGGGCGGCGGCGGGGGGCGGCGGCGGGGGGGCTGTTCCTCCTTATCTGGAGCTGGCCGGGCCGCCATTTTTGTTGTTAACCCTGATCCGGATCGGGTTGGGGAGGAGGAGCGGCCGCGCGGGCGGGCGGGCGGGAACGCAGTGTGGCGGGGAGCGGGGGCCCGGCTTCGCGGCATTTCGCCCTCTCCGGCCCTTCCGGAGGCTCCGGGTTTGTGCCGTGTGCGTGCGGGGCTCGGCGCTGGGGCGCTCGGTAGGTCTCCCGCGGGGAGGGGCGGCGGGGGCCCCGTTTTCTTCCTCCCCGGCCCCCCACCCGCGCCGTGTCTTATGTCGCTGCCTTCTCTTCCTGTTTTTCAGCTGTCACGACCGGAGGGGGGACTCGCAGCCTTACCAGGTACCAGCCGAGGCCGGGGTGGAGGGATTGGAAGGGGCCGGAGGGGGAAGGGAGGGACTGCTACTCGAGCGCAGGCCTCAGAAGTCGATACAGGCCCTTCGGTGCAACACATCTGAAACTAGCACCGCGGATCCCCTTAAAATTCCAGGTTTGGTTCCTTTAGCGCTCTCCAGCAAGGTTTAGTGACTTATTTTGACAGGTGACTGGAGGGAGTTCGCTGATTTAGGAAAAAAGAATCATTTGCAGCCAGAAAGACCTGACTCGATTATTTGATTATTTGCGAGTGAAGGAATCGATGGGATGAGATGATAGGTGACTTACGAGGCTTATTTATTTATTTATTGTGTTGGGGGAACTGAAAAGTTAATGTAAAGGTATTAAAATTAAGTGAAGAACTTGGGTAAATAGCTAAATGACTTACAACTTTCAAGTCGGTTATAAAGTACTACCCTTTCCCCTTTTAATATTTTTGGTATACTTAATTGCCTTACAAGTAAAAGATATGTGTGCTTTTGTTTCTGTAAGAATTGAGGTCTTTGGGTACTTGGATAATCATTCTGATGTAGGTGGTTCTAGGTAGGTGGGTTCCTTTTTGTTACTGCAGTCATTGTGTGTGAAGTTCTAAGGATTATGATGAAAGTGGCCCCAATTTTCAGGAGGGAAACCTCATAATGATTGTTAACCATCAGATGACTGCAGAAAACACTTTCTACATCTTAAAGGACTAGAGAGCAGGTTTCTAACCTGATGGTTGTGTTATACAGCTGAATTTGAAAACACTGTCTTCTGATATGTAAAACATTGGATATGTCAAAAATTAAACTTTACTGAATCTGTCCTCCAAAGCATAGCTGATTACACATTGCAACAGATTAGTACATCATGATTGTCTTAAGATATGTGTTAGAATAAAGCTAAACGATTATTTTGAGCGCATTATGCTTAGTTAGAAATAGTACTCACATTAGTTTATTTTGGTTAGTATTTTTATACCTTAAAATTGTTTCCCACACCTGGGAGAGTAAGGAAGTTAGGTCTGAAATGCTTTATTTGAATCAAAGAATTGGAGAAACTGGTGTGTGGGTTTTTTTTTTTTTTTTTGGTAGGTTTGCAAAAATATGCATGTGCTTATTTATACATGTGTTTGTGTATATCAGCTGTAGAGCAGAAATTGATTATAGTAGTACTGAATTTCTAGTTTTCTTTTGACTATCAAAAAATGATTCTAAATATTCTCAGCCAAATTTTTTTATTTTTTGCAGAATCAGTGTGCAAGGTGGTTTATAAGATAATGGAGTGGGTTTTTTTTGTGTTTAGTGTGATTTGTTATCAGGAGTCTTATTGTAACGCTTAAGCATTAGGTTTTTTGTCTGAGAAACTTTAAAGAGTAAAGCAGAATTGAAAGTGGAAATTTTAATTTTGTAAGTTCATAAAATTTAATGATAATACACCAAAGTTTATGTTTAAATTAGGGAGTTTAAGGTTTCAATTCTTTCTCTCTTTTTTTGGGGGGGTGATGTTTTACAGGCACTTAAGTATTCATCGAAGAGTCACCCCAGTAGCGGTGATCACAGACATGAAAAGATGCGAGACGCCGGAGATCCTTCACCACCAAATAAAATGTTGCGGAGATCTGATAGTCCTGAAAACAAATACAGTGACAGCACAGGTCACAGTAAGGCCAAAAATGTGCATACTCACAGAGTTAGAGAGAGGGATGGTGGTGAGTATCTTTCTTGTTGAAACTTTGACATACAGTTTTAACAATAGCTCTATATAAAAGGCGGCAGTAGTATTTCTAGCTTGAAGAAGTTACTGTTCAGTTATGTCATTAAAATATTTTAATCCTATCATTTTTTTTTTACTCTGAACAAGTTACTGTAGAAACAAGATGCTGATGTGAGCATCTAAAAAGTGGACTCTTAAGGCCAGGCGCGGTGGCTCACGCCTGTAATCTCAGCACTTGGGAGGCCGAGGCGGGCAGATCACCTGAGGTCAGGAGTTCAAGACCAGCCTGGCCAGCAGGTGAAAACCCATCTCTACTAAAAATACAAAAGTTAGTTGGGCATGGTGGTGGTGGCAGGCGCCTGTAGTGCCAGCTCTTCAGGAAGCTAAGGTAGGAGAATCACTTGAACCTGGTTGGTGGAGGTTGCAGTCAGCCTGAGATGGTGCCACTGCACTCCAGCCTGGGTGCTAGAGTGAGACTCCATTAAAAAAAAAAAAAAAGCGGACTTTAGTGTTTAATAATAAGGGAATGCATTTATGAATATAGTTTAAAACATGCTTTCTTAAGGATGGGAAAAATGCAGGACTTTTTTCCAAGAAAGGAACTTTGACCTTTTAAAGATTTCAGTTTGAGATCCTTATTGTTGCTTCAGTTTGTTACTTTTTAAGGTGTTCAAATCTGTTTTCTAATTACAATGATAAACTATGAATTTAAAAACTCATTATGTTTTTTCAGGATAGTTCCCAGATTTAAAAAATTATTTATGACTTAGAAAATACATTCTTGCTTTTTGTTGTAAACATTTTCAGTATTCTCCAGTTTTGGTGATGTGATTTTTATACCTGGTTCATTGAAATATTCTTTTTAAAAGTTAGTCTGATTTCTTTTGCACAGTCCTGTACCTTCAATTATAAGTTTGCCTCAAGCTCTTTGTGGTAGGAGTCTGAGAATAAGTAAACAAAACCAATTCTCAGTAACTATTTTCAGACTTAATTTGCCCGAATTACATTTCATGTCAAAAGCATGCATTAAGGAACAAAGCAATTTCAGTAAAGACACCTATATTCTCTCCTACATGTTGCTTAAGTAGATAACATATCTTAAGCAGATTTACAATATTAAAAGCTTCCAAGGAAACTCAGTAAAGTACCATGTGACTTTTTGCCCCTATTGGCAGCTAGTTCTTCAATACTTGGCTTACTTTAAAAAAAATACCTTGCATCTTGCCCCTTTTGTCCACCTAGGATAGAAATCAGCTTTATTCAGTGTGATCATATACTGAGAAACATTGGCTTCCTCTACATAATTACTGGTTTGAGAAAATACAGTCAGAAGATTGCACTGGGATTGAATAATTTGGATGAGAAGAAAGTAGTTCTCTATTGAATGTAGTTATAGCTTAGTGCTATTTATGCAGATAAACCACATTTTTGTAACAGTAGTAGCAGGTGTATTTGATTATTAAAGTGTTACAAGTTATTGGGTTGCAAAATTAAGCTTTTAGAGTTATCAGTTTTGTGGGTAAGTTTTCCATAGTATTATGTAAAGCCTGAGATGGTACTCTCTATCAACCACTCTTCTATAGTGGATTTCATTTCTAATGTTAGCTCTTGGAGAGCAGGTACTGGTTGTACTATACTGTATTTATTTTGAAAAATTTGGTGATTGTAACAAAATAGGATATGGCACCTCATCTTCTTACAAATAGGCTCTTATTTTAGTGACTATGATCCAGTTTATCCCCAAATGCAAGAAGTCAGTTTTTCAGTTATAAATGCTTTCAATCATTTCCAGCAAACCTTGCTCAGCCAATTCTTTTACAGGTGAAGTAATCCCAAGAACATTCTGTTGCTTATTCATTCAACAAACCTGGGGCATCTACTGTGTGCCAACATTTGTGTGATACTCCTGGGAGTCAAGATGTGATCCTGGCCTTGAAGCTATTCTTAAATGCTTTGACTCTTGAGAGCTAGTGGTGTTTTAGCCACTTACTTTTTCTGTACCCATTTTTTCTTCACTTTGATTTTTTCATTTTTCTACCTGTATGAACTCCAGGTACTTGTTAGCTTTTCGTTTTTAAAAATTTGCATCTTTCCTGATGTTTCTTTAGCTTCATTTGCAAGAAACTTGATGTTTTTCTGATCTAATCACTTGCTAAGTTAGGCCCCACTTTCCAATTTTCTTTCTAGCTGATTGTCGTCTTCTGGAGTCTTCCAGCTAATACTGTGATTCCATTCCTGTCTCTACCATCTCTAACATACCTGGCTGCCATATTCCTTTATATTATATGGAAATAATAATATGAGGTATATCTCCATTCTGGAATTGAGAGTACATCTTTGATATTCTCTCTTCAAAAAACGTAAAATGGTGATTTTTCCTCATTTTATAGTGAGATATTTAGTCATTATAATTTGTTTTCTGGTGTTTATTTTTTATTGCTAATGATGTGTTTGGCACTAAGATGTTAAAAGTGTATATGTATGATTTTTATTGCAGGCATTATAAACTCCTTTGGATTTTTATCCAAAAATGAATTCAGGCCGGGTCAGTGGCTCACGCCGGAATCTCAGCACTTTGGGAGGCCGAGGCAGGCAGATCACCTGAGGTCAGGAGTTTGAGACCAGCCTGGCCAACGTGGTGAAACCCTGTCTCTACTACAAATACAAAAGTTAGCTGGTTGCGGTGGCGAGTGCCTGTAATCCCAACTACTAGGGAGGCTGAGGCAGGAAAATCACTTGAACCCAGGAGGTGGAGGTTGCAGTGAGCTGAGATTGTGCCATTGCACTCCAGCCTGGGAGACGGATTGAGACCCTGTCTCAAAAAAAAAAAAAAAAAAAAGAATTCAGCCAGGCACAGCTGCTCATCTCTGTAATGCTGGTTGCTTGGGAGGTTGAGATGGGAAGGTCCTTTGAAGCCAGGAGTTTGAGACTAGCCTTGGCAACATAGCAAGACCCTGTGTCTACTAAAAAAAAAAAAAATTTTTTTTTTGATTAGCTGGGTGTGGTGGGATGATTGCTTGAGCCCAGGAGTTTGAGGTTAACAGTGAGCTGTGGTTGTGCCACCACACTCTAACCTGGGTTGATAGAGTGAGACCCGTCTGTTTAAAAAAAAAAAAAAAAAAGAAAAAAATTAATGTATATAAATTCAAGACCATTATCAAAAATCAAATGCAAGTGAGTTGGATTATCTAAGCTCTAAGCATGTAAAAAACTTAAGATTACAGCAGGTTACTTACTATATGCATTGAACTACTGAATTCAAATTTCCCAGTTTTTCATTTTAAGATTTAATGATTTTCTTTACTAATAATAACCTATATGCTATGATTTGTAACTTGCATTTTACAAAGCAAGTTAAATGTGGAACTTGTGCGTTTGTTTACCTTAGGATTAGGCTTTACTGGCATCACAGCATTTTTCAGTAATTACTAGATTTCTTAGCATCTTGGATTTCATTGAAAAATGCTCGTTCAGAAGTAATGTATGAAAGGACTTGCAGATACAATATAAAAAGTGAGAAATCAGGGATTGTGAAGGTTTTTATTCCCAAAAACCTTGCTAGTTAAAATAAGACTTGCTGTAACATAGCGTGTATAGTTTAGAGTTAGAGATTTTATCCATTAGGATTTATTAAAGGAAATAATGTCTATTGTAAATTTAAGATAGGTTATGTGAGAGTATAATTAAAATATTTTTTTGTGAAATGAGTTATTTTTATATAGTCTGTGATCTGTCTGAAAACATACAATCTTGTTTAAAGTAACCAAAAGCAAAAACCTTAAGGTACAATCGTTAGGGTTTGTTTTTTGGTTTTTTTTTTTCTGGAGACAGAGTTGCCCAGGCTGGAGTGCAGTGGTGTG'],
      dtype=object)

In [ ]:
valid_bases = ['A', 'T', 'C', 'G']

df_hg38 = df_hg38[
    df["ReferenceAlleleVCF"].isin(valid_bases) &
    df["AlternateAlleleVCF"].isin(valid_bases)
]

<ipython-input-16-f6acce0d505a>:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_hg38 = df_hg38[

In [ ]:
print("After cleaning df_hg38:", df_hg38.shape)

After cleaning df_hg38: (3115046, 43)

In [ ]:
df_hg38["AlternateAlleleVCF"].unique()

array(['A', 'T', 'G', 'C'], dtype=object)

In [ ]:
df_hg38["ReferenceAlleleVCF"].unique()

array(['G', 'C', 'A', 'T'], dtype=object)

In [ ]:
df_hg38['AlternateAllele'] = df_hg38['AlternateAlleleVCF'].str.upper()
df_hg38['ReferenceAllele'] = df_hg38['ReferenceAlleleVCF'].str.upper()

In [ ]:
df_hg38.drop(columns=['ReferenceAlleleVCF', 'AlternateAlleleVCF'], inplace=True)

In [ ]:
df_hg38

In [ ]:
df_hg38['ClinicalSignificance'].unique()

In [ ]:
df_hg38['Type'].unique()

array(['single nucleotide variant', 'Variation', 'Deletion',
       'Duplication'], dtype=object)

In [ ]:
df_hg38 = df_hg38[df_hg38['Type'] == 'single nucleotide variant']

In [ ]:
df_hg38 = df_hg38[df_hg38['ClinicalSignificance'].isin(['Pathogenic', 'Benign'])]

In [ ]:
df_hg38['label'] = df_hg38['ClinicalSignificance'].map({'Pathogenic': 1, 'Benign': 0})

<ipython-input-27-2b70a70abeb7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hg38['label'] = df_hg38['ClinicalSignificance'].map({'Pathogenic': 1, 'Benign': 0})

In [ ]:
df_filtered = df_hg38[['Chromosome', 'Start', 'ReferenceAllele', 'AlternateAllele', 'GeneSymbol', 'label']]

In [ ]:
df_filtered.to_csv("clinvar_snvs_filtered.csv", index=False)

In [ ]:
df_filtered

,Chromosome,Start,ReferenceAllele,AlternateAllele,GeneSymbol,label
7,11,126275389,C,T,FOXRED1,1
23,6,26093008,G,A,HFE,0
31,6,26093215,G,T,HFE,1
35,2,19989284,T,C,WDR35,1
37,2,19945787,T,C,WDR35,1
...,...,...,...,...,...,...
6865973,16,29990867,C,A,TAOK2,1
6866015,8,15659648,G,C,TUSC3,1
6866017,X,77684291,G,C,ATRX,1
6866019,8,60856514,G,T,CHD7,1
6866027,3,45973225,C,T,FYCO1,1

In [ ]:
!pip install pyfaidx

In [ ]:
from pyfaidx import Fasta
import pandas as pd

# Load the reference genome
genome = Fasta("hg38.fa")

# Load your mutation dataset
df = pd.read_csv("clinvar_snvs_filtered.csv")
print(df.head())

  Chromosome      Start ReferenceAllele AlternateAllele GeneSymbol  label
0         11  126275389               C               T    FOXRED1      1
1          6   26093008               G               A        HFE      0
2          6   26093215               G               T        HFE      1
3          2   19989284               T               C      WDR35      1
4          2   19945787               T               C      WDR35      1

In [ ]:
# Check which chromosomes from df_clean are NOT in genome
df['Chromosome'] = 'chr' + df['Chromosome'].astype(str)
missing_chroms = set(df['Chromosome']) - set(genome.keys())
print("Missing Chromosomes:", missing_chroms)

Missing Chromosomes: {'chrMT'}

In [ ]:
df.head()

  Chromosome      Start ReferenceAllele AlternateAllele GeneSymbol  label
0      chr11  126275389               C               T    FOXRED1      1
1       chr6   26093008               G               A        HFE      0
2       chr6   26093215               G               T        HFE      1
3       chr2   19989284               T               C      WDR35      1
4       chr2   19945787               T               C      WDR35      1

In [ ]:
df["Chromosome"].unique()

array(['chr11', 'chr6', 'chr2', 'chr20', 'chr10', 'chr19', 'chr16',
       'chr22', 'chr1', 'chr8', 'chr14', 'chr21', 'chr5', 'chr4', 'chr18',
       'chr15', 'chr3', 'chr17', 'chr12', 'chr7', 'chr9', 'chr13',
       'chrMT', 'chrY', 'chrX'], dtype=object)

In [ ]:
genome.keys()

odict_keys(['chr1', 'chr10', 'chr11', 'chr11_KI270721v1_random', 'chr12', 'chr13', 'chr14', 'chr14_GL000009v2_random', 'chr14_GL000225v1_random', 'chr14_KI270722v1_random', 'chr14_GL000194v1_random', 'chr14_KI270723v1_random', 'chr14_KI270724v1_random', 'chr14_KI270725v1_random', 'chr14_KI270726v1_random', 'chr15', 'chr15_KI270727v1_random', 'chr16', 'chr16_KI270728v1_random', 'chr17', 'chr17_GL000205v2_random', 'chr17_KI270729v1_random', 'chr17_KI270730v1_random', 'chr18', 'chr19', 'chr1_KI270706v1_random', 'chr1_KI270707v1_random', 'chr1_KI270708v1_random', 'chr1_KI270709v1_random', 'chr1_KI270710v1_random', 'chr1_KI270711v1_random', 'chr1_KI270712v1_random', 'chr1_KI270713v1_random', 'chr1_KI270714v1_random', 'chr2', 'chr20', 'chr21', 'chr22', 'chr22_KI270731v1_random', 'chr22_KI270732v1_random', 'chr22_KI270733v1_random', 'chr22_KI270734v1_random', 'chr22_KI270735v1_random', 'chr22_KI270736v1_random', 'chr22_KI270737v1_random', 'chr22_KI270738v1_random', 'chr22_KI270739v1_random', 'chr2_KI270715v1_random', 'chr2_KI270716v1_random', 'chr3', 'chr3_GL000221v1_random', 'chr4', 'chr4_GL000008v2_random', 'chr5', 'chr5_GL000208v1_random', 'chr6', 'chr7', 'chr8', 'chr9', 'chr9_KI270717v1_random', 'chr9_KI270718v1_random', 'chr9_KI270719v1_random', 'chr9_KI270720v1_random', 'chr1_KI270762v1_alt', 'chr1_KI270766v1_alt', 'chr1_KI270760v1_alt', 'chr1_KI270765v1_alt', 'chr1_GL383518v1_alt', 'chr1_GL383519v1_alt', 'chr1_GL383520v2_alt', 'chr1_KI270764v1_alt', 'chr1_KI270763v1_alt', 'chr1_KI270759v1_alt', 'chr1_KI270761v1_alt', 'chr2_KI270770v1_alt', 'chr2_KI270773v1_alt', 'chr2_KI270774v1_alt', 'chr2_KI270769v1_alt', 'chr2_GL383521v1_alt', 'chr2_KI270772v1_alt', 'chr2_KI270775v1_alt', 'chr2_KI270771v1_alt', 'chr2_KI270768v1_alt', 'chr2_GL582966v2_alt', 'chr2_GL383522v1_alt', 'chr2_KI270776v1_alt', 'chr2_KI270767v1_alt', 'chr3_JH636055v2_alt', 'chr3_KI270783v1_alt', 'chr3_KI270780v1_alt', 'chr3_GL383526v1_alt', 'chr3_KI270777v1_alt', 'chr3_KI270778v1_alt', 'chr3_KI270781v1_alt', 'chr3_KI270779v1_alt', 'chr3_KI270782v1_alt', 'chr3_KI270784v1_alt', 'chr4_KI270790v1_alt', 'chr4_GL383528v1_alt', 'chr4_KI270787v1_alt', 'chr4_GL000257v2_alt', 'chr4_KI270788v1_alt', 'chr4_GL383527v1_alt', 'chr4_KI270785v1_alt', 'chr4_KI270789v1_alt', 'chr4_KI270786v1_alt', 'chr5_KI270793v1_alt', 'chr5_KI270792v1_alt', 'chr5_KI270791v1_alt', 'chr5_GL383532v1_alt', 'chr5_GL949742v1_alt', 'chr5_KI270794v1_alt', 'chr5_GL339449v2_alt', 'chr5_GL383530v1_alt', 'chr5_KI270796v1_alt', 'chr5_GL383531v1_alt', 'chr5_KI270795v1_alt', 'chr6_GL000250v2_alt', 'chr6_KI270800v1_alt', 'chr6_KI270799v1_alt', 'chr6_GL383533v1_alt', 'chr6_KI270801v1_alt', 'chr6_KI270802v1_alt', 'chr6_KB021644v2_alt', 'chr6_KI270797v1_alt', 'chr6_KI270798v1_alt', 'chr7_KI270804v1_alt', 'chr7_KI270809v1_alt', 'chr7_KI270806v1_alt', 'chr7_GL383534v2_alt', 'chr7_KI270803v1_alt', 'chr7_KI270808v1_alt', 'chr7_KI270807v1_alt', 'chr7_KI270805v1_alt', 'chr8_KI270818v1_alt', 'chr8_KI270812v1_alt', 'chr8_KI270811v1_alt', 'chr8_KI270821v1_alt', 'chr8_KI270813v1_alt', 'chr8_KI270822v1_alt', 'chr8_KI270814v1_alt', 'chr8_KI270810v1_alt', 'chr8_KI270819v1_alt', 'chr8_KI270820v1_alt', 'chr8_KI270817v1_alt', 'chr8_KI270816v1_alt', 'chr8_KI270815v1_alt', 'chr9_GL383539v1_alt', 'chr9_GL383540v1_alt', 'chr9_GL383541v1_alt', 'chr9_GL383542v1_alt', 'chr9_KI270823v1_alt', 'chr10_GL383545v1_alt', 'chr10_KI270824v1_alt', 'chr10_GL383546v1_alt', 'chr10_KI270825v1_alt', 'chr11_KI270832v1_alt', 'chr11_KI270830v1_alt', 'chr11_KI270831v1_alt', 'chr11_KI270829v1_alt', 'chr11_GL383547v1_alt', 'chr11_JH159136v1_alt', 'chr11_JH159137v1_alt', 'chr11_KI270827v1_alt', 'chr11_KI270826v1_alt', 'chr12_GL877875v1_alt', 'chr12_GL877876v1_alt', 'chr12_KI270837v1_alt', 'chr12_GL383549v1_alt', 'chr12_KI270835v1_alt', 'chr12_GL383550v2_alt', 'chr12_GL383552v1_alt', 'chr12_GL383553v2_alt', 'chr12_KI270834v1_alt', 'chr12_GL383551v1_alt', 'chr12_KI270833v1_alt', 'chr12_KI270836v1_alt', 'chr13_KI270840v1_alt', 'chr13_KI270839v1_alt', 'chr13_KI270843v1_alt', 'chr13_KI270841v1_alt', 'chr13_KI270838v1_alt', 'chr13_KI270842v1_alt', 'chr14_KI270844v1_alt', 'chr14_KI270847v1_alt', 'chr14_KI270845v1_alt', 'chr14_KI270846v1_alt', 'chr15_KI270852v1_alt', 'chr15_KI270851v1_alt', 'chr15_KI270848v1_alt', 'chr15_GL383554v1_alt', 'chr15_KI270849v1_alt', 'chr15_GL383555v2_alt', 'chr15_KI270850v1_alt', 'chr16_KI270854v1_alt', 'chr16_KI270856v1_alt', 'chr16_KI270855v1_alt', 'chr16_KI270853v1_alt', 'chr16_GL383556v1_alt', 'chr16_GL383557v1_alt', 'chr17_GL383563v3_alt', 'chr17_KI270862v1_alt', 'chr17_KI270861v1_alt', 'chr17_KI270857v1_alt', 'chr17_JH159146v1_alt', 'chr17_JH159147v1_alt', 'chr17_GL383564v2_alt', 'chr17_GL000258v2_alt', 'chr17_GL383565v1_alt', 'chr17_KI270858v1_alt', 'chr17_KI270859v1_alt', 'chr17_GL383566v1_alt', 'chr17_KI270860v1_alt', 'chr18_KI270864v1_alt', 'chr18_GL383567v1_alt', 'chr18_GL383570v1_alt', 'chr18_GL383571v1_alt', 'chr18_GL383568v1_alt', 'chr18_GL383569v1_alt', 'chr18_GL383572v1_alt', 'chr18_KI270863v1_alt', 'chr19_KI270868v1_alt', 'chr19_KI270865v1_alt', 'chr19_GL383573v1_alt', 'chr19_GL383575v2_alt', 'chr19_GL383576v1_alt', 'chr19_GL383574v1_alt', 'chr19_KI270866v1_alt', 'chr19_KI270867v1_alt', 'chr19_GL949746v1_alt', 'chr20_GL383577v2_alt', 'chr20_KI270869v1_alt', 'chr20_KI270871v1_alt', 'chr20_KI270870v1_alt', 'chr21_GL383578v2_alt', 'chr21_KI270874v1_alt', 'chr21_KI270873v1_alt', 'chr21_GL383579v2_alt', 'chr21_GL383580v2_alt', 'chr21_GL383581v2_alt', 'chr21_KI270872v1_alt', 'chr22_KI270875v1_alt', 'chr22_KI270878v1_alt', 'chr22_KI270879v1_alt', 'chr22_KI270876v1_alt', 'chr22_KI270877v1_alt', 'chr22_GL383583v2_alt', 'chr22_GL383582v2_alt', 'chrX_KI270880v1_alt', 'chrX_KI270881v1_alt', 'chr19_KI270882v1_alt', 'chr19_KI270883v1_alt', 'chr19_KI270884v1_alt', 'chr19_KI270885v1_alt', 'chr19_KI270886v1_alt', 'chr19_KI270887v1_alt', 'chr19_KI270888v1_alt', 'chr19_KI270889v1_alt', 'chr19_KI270890v1_alt', 'chr19_KI270891v1_alt', 'chr1_KI270892v1_alt', 'chr2_KI270894v1_alt', 'chr2_KI270893v1_alt', 'chr3_KI270895v1_alt', 'chr4_KI270896v1_alt', 'chr5_KI270897v1_alt', 'chr5_KI270898v1_alt', 'chr6_GL000251v2_alt', 'chr7_KI270899v1_alt', 'chr8_KI270901v1_alt', 'chr8_KI270900v1_alt', 'chr11_KI270902v1_alt', 'chr11_KI270903v1_alt', 'chr12_KI270904v1_alt', 'chr15_KI270906v1_alt', 'chr15_KI270905v1_alt', 'chr17_KI270907v1_alt', 'chr17_KI270910v1_alt', 'chr17_KI270909v1_alt', 'chr17_JH159148v1_alt', 'chr17_KI270908v1_alt', 'chr18_KI270912v1_alt', 'chr18_KI270911v1_alt', 'chr19_GL949747v2_alt', 'chr22_KB663609v1_alt', 'chrX_KI270913v1_alt', 'chr19_KI270914v1_alt', 'chr19_KI270915v1_alt', 'chr19_KI270916v1_alt', 'chr19_KI270917v1_alt', 'chr19_KI270918v1_alt', 'chr19_KI270919v1_alt', 'chr19_KI270920v1_alt', 'chr19_KI270921v1_alt', 'chr19_KI270922v1_alt', 'chr19_KI270923v1_alt', 'chr3_KI270924v1_alt', 'chr4_KI270925v1_alt', 'chr6_GL000252v2_alt', 'chr8_KI270926v1_alt', 'chr11_KI270927v1_alt', 'chr19_GL949748v2_alt', 'chr22_KI270928v1_alt', 'chr19_KI270929v1_alt', 'chr19_KI270930v1_alt', 'chr19_KI270931v1_alt', 'chr19_KI270932v1_alt', 'chr19_KI270933v1_alt', 'chr19_GL000209v2_alt', 'chr3_KI270934v1_alt', 'chr6_GL000253v2_alt', 'chr19_GL949749v2_alt', 'chr3_KI270935v1_alt', 'chr6_GL000254v2_alt', 'chr19_GL949750v2_alt', 'chr3_KI270936v1_alt', 'chr6_GL000255v2_alt', 'chr19_GL949751v2_alt', 'chr3_KI270937v1_alt', 'chr6_GL000256v2_alt', 'chr19_GL949752v1_alt', 'chr6_KI270758v1_alt', 'chr19_GL949753v2_alt', 'chr19_KI270938v1_alt', 'chrM', 'chrUn_KI270302v1', 'chrUn_KI270304v1', 'chrUn_KI270303v1', 'chrUn_KI270305v1', 'chrUn_KI270322v1', 'chrUn_KI270320v1', 'chrUn_KI270310v1', 'chrUn_KI270316v1', 'chrUn_KI270315v1', 'chrUn_KI270312v1', 'chrUn_KI270311v1', 'chrUn_KI270317v1', 'chrUn_KI270412v1', 'chrUn_KI270411v1', 'chrUn_KI270414v1', 'chrUn_KI270419v1', 'chrUn_KI270418v1', 'chrUn_KI270420v1', 'chrUn_KI270424v1', 'chrUn_KI270417v1', 'chrUn_KI270422v1', 'chrUn_KI270423v1', 'chrUn_KI270425v1', 'chrUn_KI270429v1', 'chrUn_KI270442v1', 'chrUn_KI270466v1', 'chrUn_KI270465v1', 'chrUn_KI270467v1', 'chrUn_KI270435v1', 'chrUn_KI270438v1', 'chrUn_KI270468v1', 'chrUn_KI270510v1', 'chrUn_KI270509v1', 'chrUn_KI270518v1', 'chrUn_KI270508v1', 'chrUn_KI270516v1', 'chrUn_KI270512v1', 'chrUn_KI270519v1', 'chrUn_KI270522v1', 'chrUn_KI270511v1', 'chrUn_KI270515v1', 'chrUn_KI270507v1', 'chrUn_KI270517v1', 'chrUn_KI270529v1', 'chrUn_KI270528v1', 'chrUn_KI270530v1', 'chrUn_KI270539v1', 'chrUn_KI270538v1', 'chrUn_KI270544v1', 'chrUn_KI270548v1', 'chrUn_KI270583v1', 'chrUn_KI270587v1', 'chrUn_KI270580v1', 'chrUn_KI270581v1', 'chrUn_KI270579v1', 'chrUn_KI270589v1', 'chrUn_KI270590v1', 'chrUn_KI270584v1', 'chrUn_KI270582v1', 'chrUn_KI270588v1', 'chrUn_KI270593v1', 'chrUn_KI270591v1', 'chrUn_KI270330v1', 'chrUn_KI270329v1', 'chrUn_KI270334v1', 'chrUn_KI270333v1', 'chrUn_KI270335v1', 'chrUn_KI270338v1', 'chrUn_KI270340v1', 'chrUn_KI270336v1', 'chrUn_KI270337v1', 'chrUn_KI270363v1', 'chrUn_KI270364v1', 'chrUn_KI270362v1', 'chrUn_KI270366v1', 'chrUn_KI270378v1', 'chrUn_KI270379v1', 'chrUn_KI270389v1', 'chrUn_KI270390v1', 'chrUn_KI270387v1', 'chrUn_KI270395v1', 'chrUn_KI270396v1', 'chrUn_KI270388v1', 'chrUn_KI270394v1', 'chrUn_KI270386v1', 'chrUn_KI270391v1', 'chrUn_KI270383v1', 'chrUn_KI270393v1', 'chrUn_KI270384v1', 'chrUn_KI270392v1', 'chrUn_KI270381v1', 'chrUn_KI270385v1', 'chrUn_KI270382v1', 'chrUn_KI270376v1', 'chrUn_KI270374v1', 'chrUn_KI270372v1', 'chrUn_KI270373v1', 'chrUn_KI270375v1', 'chrUn_KI270371v1', 'chrUn_KI270448v1', 'chrUn_KI270521v1', 'chrUn_GL000195v1', 'chrUn_GL000219v1', 'chrUn_GL000220v1', 'chrUn_GL000224v1', 'chrUn_KI270741v1', 'chrUn_GL000226v1', 'chrUn_GL000213v1', 'chrUn_KI270743v1', 'chrUn_KI270744v1', 'chrUn_KI270745v1', 'chrUn_KI270746v1', 'chrUn_KI270747v1', 'chrUn_KI270748v1', 'chrUn_KI270749v1', 'chrUn_KI270750v1', 'chrUn_KI270751v1', 'chrUn_KI270752v1', 'chrUn_KI270753v1', 'chrUn_KI270754v1', 'chrUn_KI270755v1', 'chrUn_KI270756v1', 'chrUn_KI270757v1', 'chrUn_GL000214v1', 'chrUn_KI270742v1', 'chrUn_GL000216v2', 'chrUn_GL000218v1', 'chrX', 'chrY', 'chrY_KI270740v1_random'])

In [ ]:
# Function to test ref match
def check_ref_mismatch(row):
    try:
        chrom = row['Chromosome']
        pos = int(row['Start'])
        ref = row['ReferenceAllele'].upper()
        genome_ref = genome[chrom][pos - 1].seq.upper()
        return genome_ref != ref
    except:
        return True

df['RefMismatch'] = df.apply(check_ref_mismatch, axis=1)
print("Ref mismatches:", df['RefMismatch'].sum())

Ref mismatches: 1007

In [ ]:
# Fix chromosome names properly
df['Chromosome'] = df['Chromosome'].apply(lambda x: x if str(x).startswith('chr') else f'chr{x}')

In [ ]:
df["Chromosome"].unique()

array(['chr11', 'chr6', 'chr2', 'chr20', 'chr10', 'chr19', 'chr16',
       'chr22', 'chr1', 'chr8', 'chr14', 'chr21', 'chr5', 'chr4', 'chr18',
       'chr15', 'chr3', 'chr17', 'chr12', 'chr7', 'chr9', 'chr13',
       'chrMT', 'chrY', 'chrX'], dtype=object)

In [ ]:
df

,Chromosome,Start,ReferenceAllele,AlternateAllele,GeneSymbol,label,RefMismatch
0,chr11,126275389,C,T,FOXRED1,1,False
1,chr6,26093008,G,A,HFE,0,False
2,chr6,26093215,G,T,HFE,1,False
3,chr2,19989284,T,C,WDR35,1,False
4,chr2,19945787,T,C,WDR35,1,False
...,...,...,...,...,...,...,...
261578,chr16,29990867,C,A,TAOK2,1,False
261579,chr8,15659648,G,C,TUSC3,1,False
261580,chrX,77684291,G,C,ATRX,1,False
261581,chr8,60856514,G,T,CHD7,1,False
261582,chr3,45973225,C,T,FYCO1,1,False

In [ ]:
df['RefMismatch'].value_counts()

RefMismatch
False    260576
True       1007
Name: count, dtype: int64

In [ ]:
def is_valid_ref(row):
    try:
        genome_base = genome[row['Chromosome']][int(row['Start']) - 1].seq.upper()
        return genome_base == row['ReferenceAllele'].upper()
    except:
        return False

df_valid = df[df.apply(is_valid_ref, axis=1)].copy()
print(f"Valid entries: {len(df_valid)}")

Valid entries: 260576

In [ ]:
!grep ">" hg38.fa

>chr1
>chr10
>chr11
>chr11_KI270721v1_random
>chr12
>chr13
>chr14
>chr14_GL000009v2_random
>chr14_GL000225v1_random
>chr14_KI270722v1_random
>chr14_GL000194v1_random
>chr14_KI270723v1_random
>chr14_KI270724v1_random
>chr14_KI270725v1_random
>chr14_KI270726v1_random
>chr15
>chr15_KI270727v1_random
>chr16
>chr16_KI270728v1_random
>chr17
>chr17_GL000205v2_random
>chr17_KI270729v1_random
>chr17_KI270730v1_random
>chr18
>chr19
>chr1_KI270706v1_random
>chr1_KI270707v1_random
>chr1_KI270708v1_random
>chr1_KI270709v1_random
>chr1_KI270710v1_random
>chr1_KI270711v1_random
>chr1_KI270712v1_random
>chr1_KI270713v1_random
>chr1_KI270714v1_random
>chr2
>chr20
>chr21
>chr22
>chr22_KI270731v1_random
>chr22_KI270732v1_random
>chr22_KI270733v1_random
>chr22_KI270734v1_random
>chr22_KI270735v1_random
>chr22_KI270736v1_random
>chr22_KI270737v1_random
>chr22_KI270738v1_random
>chr22_KI270739v1_random
>chr2_KI270715v1_random
>chr2_KI270716v1_random
>chr3
>chr3_GL000221v1_random
>chr4
>chr4_GL000008v2_random
>chr5
>chr5_GL000208v1_random
>chr6
>chr7
>chr8
>chr9
>chr9_KI270717v1_random
>chr9_KI270718v1_random
>chr9_KI270719v1_random
>chr9_KI270720v1_random
>chr1_KI270762v1_alt
>chr1_KI270766v1_alt
>chr1_KI270760v1_alt
>chr1_KI270765v1_alt
>chr1_GL383518v1_alt
>chr1_GL383519v1_alt
>chr1_GL383520v2_alt
>chr1_KI270764v1_alt
>chr1_KI270763v1_alt
>chr1_KI270759v1_alt
>chr1_KI270761v1_alt
>chr2_KI270770v1_alt
>chr2_KI270773v1_alt
>chr2_KI270774v1_alt
>chr2_KI270769v1_alt
>chr2_GL383521v1_alt
>chr2_KI270772v1_alt
>chr2_KI270775v1_alt
>chr2_KI270771v1_alt
>chr2_KI270768v1_alt
>chr2_GL582966v2_alt
>chr2_GL383522v1_alt
>chr2_KI270776v1_alt
>chr2_KI270767v1_alt
>chr3_JH636055v2_alt
>chr3_KI270783v1_alt
>chr3_KI270780v1_alt
>chr3_GL383526v1_alt
>chr3_KI270777v1_alt
>chr3_KI270778v1_alt
>chr3_KI270781v1_alt
>chr3_KI270779v1_alt
>chr3_KI270782v1_alt
>chr3_KI270784v1_alt
>chr4_KI270790v1_alt
>chr4_GL383528v1_alt
>chr4_KI270787v1_alt
>chr4_GL000257v2_alt
>chr4_KI270788v1_alt
>chr4_GL383527v1_alt
>chr4_KI270785v1_alt
>chr4_KI270789v1_alt
>chr4_KI270786v1_alt
>chr5_KI270793v1_alt
>chr5_KI270792v1_alt
>chr5_KI270791v1_alt
>chr5_GL383532v1_alt
>chr5_GL949742v1_alt
>chr5_KI270794v1_alt
>chr5_GL339449v2_alt
>chr5_GL383530v1_alt
>chr5_KI270796v1_alt
>chr5_GL383531v1_alt
>chr5_KI270795v1_alt
>chr6_GL000250v2_alt
>chr6_KI270800v1_alt
>chr6_KI270799v1_alt
>chr6_GL383533v1_alt
>chr6_KI270801v1_alt
>chr6_KI270802v1_alt
>chr6_KB021644v2_alt
>chr6_KI270797v1_alt
>chr6_KI270798v1_alt
>chr7_KI270804v1_alt
>chr7_KI270809v1_alt
>chr7_KI270806v1_alt
>chr7_GL383534v2_alt
>chr7_KI270803v1_alt
>chr7_KI270808v1_alt
>chr7_KI270807v1_alt
>chr7_KI270805v1_alt
>chr8_KI270818v1_alt
>chr8_KI270812v1_alt
>chr8_KI270811v1_alt
>chr8_KI270821v1_alt
>chr8_KI270813v1_alt
>chr8_KI270822v1_alt
>chr8_KI270814v1_alt
>chr8_KI270810v1_alt
>chr8_KI270819v1_alt
>chr8_KI270820v1_alt
>chr8_KI270817v1_alt
>chr8_KI270816v1_alt
>chr8_KI270815v1_alt
>chr9_GL383539v1_alt
>chr9_GL383540v1_alt
>chr9_GL383541v1_alt
>chr9_GL383542v1_alt
>chr9_KI270823v1_alt
>chr10_GL383545v1_alt
>chr10_KI270824v1_alt
>chr10_GL383546v1_alt
>chr10_KI270825v1_alt
>chr11_KI270832v1_alt
>chr11_KI270830v1_alt
>chr11_KI270831v1_alt
>chr11_KI270829v1_alt
>chr11_GL383547v1_alt
>chr11_JH159136v1_alt
>chr11_JH159137v1_alt
>chr11_KI270827v1_alt
>chr11_KI270826v1_alt
>chr12_GL877875v1_alt
>chr12_GL877876v1_alt
>chr12_KI270837v1_alt
>chr12_GL383549v1_alt
>chr12_KI270835v1_alt
>chr12_GL383550v2_alt
>chr12_GL383552v1_alt
>chr12_GL383553v2_alt
>chr12_KI270834v1_alt
>chr12_GL383551v1_alt
>chr12_KI270833v1_alt
>chr12_KI270836v1_alt
>chr13_KI270840v1_alt
>chr13_KI270839v1_alt
>chr13_KI270843v1_alt
>chr13_KI270841v1_alt
>chr13_KI270838v1_alt
>chr13_KI270842v1_alt
>chr14_KI270844v1_alt
>chr14_KI270847v1_alt
>chr14_KI270845v1_alt
>chr14_KI270846v1_alt
>chr15_KI270852v1_alt
>chr15_KI270851v1_alt
>chr15_KI270848v1_alt
>chr15_GL383554v1_alt
>chr15_KI270849v1_alt
>chr15_GL383555v2_alt
>chr15_KI270850v1_alt
>chr16_KI270854v1_alt
>chr16_KI270856v1_alt
>chr16_KI270855v1_alt
>chr16_KI270853v1_alt
>chr16_GL383556v1_alt
>chr16_GL383557v1_alt
>chr17_GL383563v3_alt
>chr17_KI270862v1_alt
>chr17_KI270861v1_alt
>chr17_KI270857v1_alt
>chr17_JH159146v1_alt
>chr17_JH159147v1_alt
>chr17_GL383564v2_alt
>chr17_GL000258v2_alt
>chr17_GL383565v1_alt
>chr17_KI270858v1_alt
>chr17_KI270859v1_alt
>chr17_GL383566v1_alt
>chr17_KI270860v1_alt
>chr18_KI270864v1_alt
>chr18_GL383567v1_alt
>chr18_GL383570v1_alt
>chr18_GL383571v1_alt
>chr18_GL383568v1_alt
>chr18_GL383569v1_alt
>chr18_GL383572v1_alt
>chr18_KI270863v1_alt
>chr19_KI270868v1_alt
>chr19_KI270865v1_alt
>chr19_GL383573v1_alt
>chr19_GL383575v2_alt
>chr19_GL383576v1_alt
>chr19_GL383574v1_alt
>chr19_KI270866v1_alt
>chr19_KI270867v1_alt
>chr19_GL949746v1_alt
>chr20_GL383577v2_alt
>chr20_KI270869v1_alt
>chr20_KI270871v1_alt
>chr20_KI270870v1_alt
>chr21_GL383578v2_alt
>chr21_KI270874v1_alt
>chr21_KI270873v1_alt
>chr21_GL383579v2_alt
>chr21_GL383580v2_alt
>chr21_GL383581v2_alt
>chr21_KI270872v1_alt
>chr22_KI270875v1_alt
>chr22_KI270878v1_alt
>chr22_KI270879v1_alt
>chr22_KI270876v1_alt
>chr22_KI270877v1_alt
>chr22_GL383583v2_alt
>chr22_GL383582v2_alt
>chrX_KI270880v1_alt
>chrX_KI270881v1_alt
>chr19_KI270882v1_alt
>chr19_KI270883v1_alt
>chr19_KI270884v1_alt
>chr19_KI270885v1_alt
>chr19_KI270886v1_alt
>chr19_KI270887v1_alt
>chr19_KI270888v1_alt
>chr19_KI270889v1_alt
>chr19_KI270890v1_alt
>chr19_KI270891v1_alt
>chr1_KI270892v1_alt
>chr2_KI270894v1_alt
>chr2_KI270893v1_alt
>chr3_KI270895v1_alt
>chr4_KI270896v1_alt
>chr5_KI270897v1_alt
>chr5_KI270898v1_alt
>chr6_GL000251v2_alt
>chr7_KI270899v1_alt
>chr8_KI270901v1_alt
>chr8_KI270900v1_alt
>chr11_KI270902v1_alt
>chr11_KI270903v1_alt
>chr12_KI270904v1_alt
>chr15_KI270906v1_alt
>chr15_KI270905v1_alt
>chr17_KI270907v1_alt
>chr17_KI270910v1_alt
>chr17_KI270909v1_alt
>chr17_JH159148v1_alt
>chr17_KI270908v1_alt
>chr18_KI270912v1_alt
>chr18_KI270911v1_alt
>chr19_GL949747v2_alt
>chr22_KB663609v1_alt
>chrX_KI270913v1_alt
>chr19_KI270914v1_alt
>chr19_KI270915v1_alt
>chr19_KI270916v1_alt
>chr19_KI270917v1_alt
>chr19_KI270918v1_alt
>chr19_KI270919v1_alt
>chr19_KI270920v1_alt
>chr19_KI270921v1_alt
>chr19_KI270922v1_alt
>chr19_KI270923v1_alt
>chr3_KI270924v1_alt
>chr4_KI270925v1_alt
>chr6_GL000252v2_alt
>chr8_KI270926v1_alt
>chr11_KI270927v1_alt
>chr19_GL949748v2_alt
>chr22_KI270928v1_alt
>chr19_KI270929v1_alt
>chr19_KI270930v1_alt
>chr19_KI270931v1_alt
>chr19_KI270932v1_alt
>chr19_KI270933v1_alt
>chr19_GL000209v2_alt
>chr3_KI270934v1_alt
>chr6_GL000253v2_alt
>chr19_GL949749v2_alt
>chr3_KI270935v1_alt
>chr6_GL000254v2_alt
>chr19_GL949750v2_alt
>chr3_KI270936v1_alt
>chr6_GL000255v2_alt
>chr19_GL949751v2_alt
>chr3_KI270937v1_alt
>chr6_GL000256v2_alt
>chr19_GL949752v1_alt
>chr6_KI270758v1_alt
>chr19_GL949753v2_alt
>chr19_KI270938v1_alt
>chrM
>chrUn_KI270302v1
>chrUn_KI270304v1
>chrUn_KI270303v1
>chrUn_KI270305v1
>chrUn_KI270322v1
>chrUn_KI270320v1
>chrUn_KI270310v1
>chrUn_KI270316v1
>chrUn_KI270315v1
>chrUn_KI270312v1
>chrUn_KI270311v1
>chrUn_KI270317v1
>chrUn_KI270412v1
>chrUn_KI270411v1
>chrUn_KI270414v1
>chrUn_KI270419v1
>chrUn_KI270418v1
>chrUn_KI270420v1
>chrUn_KI270424v1
>chrUn_KI270417v1
>chrUn_KI270422v1
>chrUn_KI270423v1
>chrUn_KI270425v1
>chrUn_KI270429v1
>chrUn_KI270442v1
>chrUn_KI270466v1
>chrUn_KI270465v1
>chrUn_KI270467v1
>chrUn_KI270435v1
>chrUn_KI270438v1
>chrUn_KI270468v1
>chrUn_KI270510v1
>chrUn_KI270509v1
>chrUn_KI270518v1
>chrUn_KI270508v1
>chrUn_KI270516v1
>chrUn_KI270512v1
>chrUn_KI270519v1
>chrUn_KI270522v1
>chrUn_KI270511v1
>chrUn_KI270515v1
>chrUn_KI270507v1
>chrUn_KI270517v1
>chrUn_KI270529v1
>chrUn_KI270528v1
>chrUn_KI270530v1
>chrUn_KI270539v1
>chrUn_KI270538v1
>chrUn_KI270544v1
>chrUn_KI270548v1
>chrUn_KI270583v1
>chrUn_KI270587v1
>chrUn_KI270580v1
>chrUn_KI270581v1
>chrUn_KI270579v1
>chrUn_KI270589v1
>chrUn_KI270590v1
>chrUn_KI270584v1
>chrUn_KI270582v1
>chrUn_KI270588v1
>chrUn_KI270593v1
>chrUn_KI270591v1
>chrUn_KI270330v1
>chrUn_KI270329v1
>chrUn_KI270334v1
>chrUn_KI270333v1
>chrUn_KI270335v1
>chrUn_KI270338v1
>chrUn_KI270340v1
>chrUn_KI270336v1
>chrUn_KI270337v1
>chrUn_KI270363v1
>chrUn_KI270364v1
>chrUn_KI270362v1
>chrUn_KI270366v1
>chrUn_KI270378v1
>chrUn_KI270379v1
>chrUn_KI270389v1
>chrUn_KI270390v1
>chrUn_KI270387v1
>chrUn_KI270395v1
>chrUn_KI270396v1
>chrUn_KI270388v1
>chrUn_KI270394v1
>chrUn_KI270386v1
>chrUn_KI270391v1
>chrUn_KI270383v1
>chrUn_KI270393v1
>chrUn_KI270384v1
>chrUn_KI270392v1
>chrUn_KI270381v1
>chrUn_KI270385v1
>chrUn_KI270382v1
>chrUn_KI270376v1
>chrUn_KI270374v1
>chrUn_KI270372v1
>chrUn_KI270373v1
>chrUn_KI270375v1
>chrUn_KI270371v1
>chrUn_KI270448v1
>chrUn_KI270521v1
>chrUn_GL000195v1
>chrUn_GL000219v1
>chrUn_GL000220v1
>chrUn_GL000224v1
>chrUn_KI270741v1
>chrUn_GL000226v1
>chrUn_GL000213v1
>chrUn_KI270743v1
>chrUn_KI270744v1
>chrUn_KI270745v1
>chrUn_KI270746v1
>chrUn_KI270747v1
>chrUn_KI270748v1
>chrUn_KI270749v1
>chrUn_KI270750v1
>chrUn_KI270751v1
>chrUn_KI270752v1
>chrUn_KI270753v1
>chrUn_KI270754v1
>chrUn_KI270755v1
>chrUn_KI270756v1
>chrUn_KI270757v1
>chrUn_GL000214v1
>chrUn_KI270742v1
>chrUn_GL000216v2
>chrUn_GL000218v1
>chrX
>chrY
>chrY_KI270740v1_random

In [ ]:
from pyfaidx import Fasta
import pandas as pd

# Load the hg38 genome (make sure .fai is generated or pyfaidx will do it)
genome = Fasta("hg38.fa")

# Ensure chromosome naming matches (e.g., '11' -> 'chr11')
# df['Chromosome'] = 'chr' + df['Chromosome'].astype(str)

# Function to get 101-bp context around the mutation site
def get_sequence(chrom, pos, ref, alt):
    try:
        # Adjust to 0-based indexing
        start = max(pos - 51, 0)
        # start = pos - 51
        end = pos + 50

        seq = genome[chrom][start:end].seq

        # Confirm the reference base matches
        ref_base = genome[chrom][pos - 1].seq.upper()
        if ref_base != ref:
            return None  # Skip if reference base does not match
        return seq.upper()
    except KeyError:
        return None  # Chromosome not found
    except Exception as e:
        return None  # Other errors

# Apply to DataFrame
df['Sequence'] = df.apply(
    lambda row: get_sequence(row['Chromosome'], int(row['Start']), row['ReferenceAllele'], row['AlternateAllele']),
    axis=1
)

# Drop rows where sequence couldn't be retrieved
df_clean = df.dropna(subset=['Sequence'])

df_clean.head()

,Chromosome,Start,ReferenceAllele,AlternateAllele,GeneSymbol,label,RefMismatch,Sequence
0,chr11,126275389,C,T,FOXRED1,1,False,AAGGTTGGTTTGACCCCTGGTGTCTGCTCCAGGGGCTTCGGCGAAA...
1,chr6,26093008,G,A,HFE,0,False,GGGGTATGTGACTGATGAGAGCCAGGAGCTGAGAAAATCTATTGGG...
2,chr6,26093215,G,T,HFE,1,False,TGCTGTTTTTGTCGTCATCTTGTTCATTGGAATTTTGTTCATAATA...
3,chr2,19989284,T,C,WDR35,1,False,CCTTGTTCCAGGATACACACTGCAGCTTCACGTTATTGGGAATGGA...
4,chr2,19945787,T,C,WDR35,1,False,TATTTGGCTCATTATTTATAGACTGTTAACACTCATTTCTTGTTTT...

In [ ]:
df_clean['RefMismatch'].value_counts()

RefMismatch
False    260576
Name: count, dtype: int64

In [ ]:
df_clean['Sequence'][1]

'GGGGTATGTGACTGATGAGAGCCAGGAGCTGAGAAAATCTATTGGGGGTTGAGAGGAGTGCCTGAGGAGGTAATTATGGCAGTGAGATGAGGATCTGCTCT'

In [ ]:
df_clean['seq_length'] = df_clean['Sequence'].apply(len)
print(df_clean['seq_length'].value_counts())

seq_length
101    260576
Name: count, dtype: int64

<ipython-input-60-9be09dc0d18f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['seq_length'] = df_clean['Sequence'].apply(len)

In [ ]:
df_clean['Chromosome'].unique()

array(['chr11', 'chr6', 'chr2', 'chr20', 'chr10', 'chr19', 'chr16',
       'chr22', 'chr1', 'chr8', 'chr14', 'chr21', 'chr5', 'chr4', 'chr18',
       'chr15', 'chr3', 'chr17', 'chr12', 'chr7', 'chr9', 'chr13', 'chrY',
       'chrX'], dtype=object)

In [ ]:
df_clean.shape

(260576, 9)

In [ ]:
df_clean

,Chromosome,Start,ReferenceAllele,AlternateAllele,GeneSymbol,label,RefMismatch,Sequence,seq_length
0,chr11,126275389,C,T,FOXRED1,1,False,AAGGTTGGTTTGACCCCTGGTGTCTGCTCCAGGGGCTTCGGCGAAA...,101
1,chr6,26093008,G,A,HFE,0,False,GGGGTATGTGACTGATGAGAGCCAGGAGCTGAGAAAATCTATTGGG...,101
2,chr6,26093215,G,T,HFE,1,False,TGCTGTTTTTGTCGTCATCTTGTTCATTGGAATTTTGTTCATAATA...,101
3,chr2,19989284,T,C,WDR35,1,False,CCTTGTTCCAGGATACACACTGCAGCTTCACGTTATTGGGAATGGA...,101
4,chr2,19945787,T,C,WDR35,1,False,TATTTGGCTCATTATTTATAGACTGTTAACACTCATTTCTTGTTTT...,101
...,...,...,...,...,...,...,...,...,...
261578,chr16,29990867,C,A,TAOK2,1,False,CAGGCCCTTCGGCAGCAGCTTCAACAGGAGCTGGAGCTGCTCAACG...,101
261579,chr8,15659648,G,C,TUSC3,1,False,TTGCAGCTGAGCAACTAGCAAAGTGGATTGCTGACAGAACGGATGT...,101
261580,chrX,77684291,G,C,ATRX,1,False,CAGAGCCAGAACAGGAATCATCTAATTTCTTTTCTTCTCCATTACA...,101
261581,chr8,60856514,G,T,CHD7,1,False,CTGTCCCTCGCCAGCGGAGGAGGAGGAGGAGAAAAATCGAAATTGA...,101
261582,chr3,45973225,C,T,FYCO1,1,False,ACAATGTCCGAGCTCAGCTTTGGCTGCAGAAAGGGGCTTCTTGCAT...,101

In [ ]:
df_clean.to_csv("mutation_sequences.csv", index=False)
print("Saved df_clean as mutation_sequences.csv")

Saved df_clean as mutation_sequences.csv

In [ ]:
import pandas as pd

# Tokenization function
def kmer_tokenizer(seq, k=6):
    return ' '.join([seq[i:i+k] for i in range(len(seq)-k+1)])

# Load the saved sequences
df = pd.read_csv("mutation_sequences.csv")

# Tokenize sequences
df['tokenized'] = df['Sequence'].apply(lambda x: kmer_tokenizer(x, k=6))

# Save the tokenized data
df.to_csv("mutation_sequences_kmer.csv", index=False)
print("Tokenized dataset saved as mutation_sequences_kmer.csv")

Tokenized dataset saved as mutation_sequences_kmer.csv

In [ ]:
df['tokenized'][1]

'GGGGTA GGGTAT GGTATG GTATGT TATGTG ATGTGA TGTGAC GTGACT TGACTG GACTGA ACTGAT CTGATG TGATGA GATGAG ATGAGA TGAGAG GAGAGC AGAGCC GAGCCA AGCCAG GCCAGG CCAGGA CAGGAG AGGAGC GGAGCT GAGCTG AGCTGA GCTGAG CTGAGA TGAGAA GAGAAA AGAAAA GAAAAT AAAATC AAATCT AATCTA ATCTAT TCTATT CTATTG TATTGG ATTGGG TTGGGG TGGGGG GGGGGT GGGGTT GGGTTG GGTTGA GTTGAG TTGAGA TGAGAG GAGAGG AGAGGA GAGGAG AGGAGT GGAGTG GAGTGC AGTGCC GTGCCT TGCCTG GCCTGA CCTGAG CTGAGG TGAGGA GAGGAG AGGAGG GGAGGT GAGGTA AGGTAA GGTAAT GTAATT TAATTA AATTAT ATTATG TTATGG TATGGC ATGGCA TGGCAG GGCAGT GCAGTG CAGTGA AGTGAG GTGAGA TGAGAT GAGATG AGATGA GATGAG ATGAGG TGAGGA GAGGAT AGGATC GGATCT GATCTG ATCTGC TCTGCT CTGCTC TGCTCT'

In [ ]:
df['seq_length'] = df['tokenized'].apply(len)
print(df['seq_length'].value_counts())

seq_length
671    260576
Name: count, dtype: int64

In [ ]:
df